services:
  backend:
    build:
      context: ./backend
    container_name: backend-box
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASS: postgres
      DB_NAME: courses
      PRIVATE_KEY_PATH: src/config/private.pem
      PUBLIC_KEY_PATH: src/config/public.pem
      FRONTEND_URL: "http://localhost:3001"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:14.8-alpine3.18"
    user: postgres
    container_name: postgres-box
    expose:
      - "5432"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "courses"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend-ui
    build:
      context: ./frontend
    ports:
      - 3001:3001

volumes:
  db:
