name: study-platform
services:
  backend:
    container_name: backend-api
    build:
      context: ./backend
    ports:
      - 3000:3000
  frontend:
    container_name: frontend-ui
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001

